Repository stfc/cloud-docker-images, pull requests merged in 2024-11, with the labels that each got.

#64 Change stale PR cut off from 90 to 30
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/tests/test_pr_message_builder.py
  cloud-chatops/version.txt
Labels: patch

#66 ChatOps - Sort thread comments by date
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/src/get_github_prs.py
  cloud-chatops/src/pr_dataclass.py
  cloud-chatops/tests/test_base_feature.py
  cloud-chatops/tests/test_get_github_prs.py
  cloud-chatops/tests/test_pr_message_builder.py
  cloud-chatops/version.txt
Labels: minor

#61 Add version check to the CI jobs
  .github/workflows/cloud_chatops.yaml
Labels: workflow

#60 Feat: Added a new cron-clone.sh script and edited the README.md file
  cloud-chatops/INSTALL.md
  cloud-chatops/chatopscron
Labels: workflow

#65 Intergration tests for ChatOps
  cloud-chatops/README.md
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/dev.py
  cloud-chatops/src/errors.py
  cloud-chatops/src/events.py
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/src/get_github_prs.py
  cloud-chatops/src/main.py
  cloud-chatops/src/pr_dataclass.py
  cloud-chatops/src/read_data.py
  cloud-chatops/tests/test_dev.py
  cloud-chatops/tests/test_events.py
  cloud-chatops/tests/test_get_github_prs.py
  cloud-chatops/tests/test_post_to_dms.py
  cloud-chatops/tests/test_pr_message_builder.py
  cloud-chatops/tests/test_pr_reminder.py
  cloud-chatops/tests/test_read_data.py
  cloud-chatops/version.txt
Labels: minor

#68 Update INSTALL.md
  cloud-chatops/INSTALL.md
Labels: documentation

#70 App manifest
  cloud-chatops/INSTALL.md
  cloud-chatops/app_manifest.yml
Labels: documentation

#73 BUG: CI Job failing on doc pr as lables aren't given
  .github/workflows/cloud_chatops.yaml
Labels: workflow

#72 Update README.md
  cloud-chatops/README.md
Labels: documentation

#74 Fix Cron Script
  cloud-chatops/INSTALL.md
  cloud-chatops/chatopscron
  cloud-chatops/docker-compose.yaml
  cloud-chatops/version.txt
Labels: major

#76 Add dev command launch
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/dev.py
  cloud-chatops/tests/test_dev.py
  cloud-chatops/version.txt
Labels: minor

#77 Remove defaults
  cloud-chatops/INSTALL.md
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/template_config.yml
  cloud-chatops/tests/test_pr_reminder.py
  cloud-chatops/tests/test_read_data.py
  cloud-chatops/version.txt
Labels: patch

#75 Refactor get prs
  cloud-chatops/docker-compose.yaml
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/src/features/post_to_dms.py
  cloud-chatops/src/features/pr_reminder.py
  cloud-chatops/src/find_prs.py
  cloud-chatops/src/get_github_prs.py
  cloud-chatops/src/pr_dataclass.py
  cloud-chatops/tests/test_base_feature.py
  cloud-chatops/tests/test_find_prs.py
  cloud-chatops/tests/test_get_github_prs.py
  cloud-chatops/tests/test_http_handler.py
  cloud-chatops/tests/test_post_to_dms.py
  cloud-chatops/tests/test_pr_dataclass.py
  cloud-chatops/tests/test_pr_message_builder.py
  cloud-chatops/tests/test_pr_reminder.py
  cloud-chatops/version.txt
Labels: minor

#82 Refactor pr reminder v2
  cloud-chatops/.pylintrc
  cloud-chatops/README.md
  cloud-chatops/docker-compose.yaml
  cloud-chatops/requirements.txt
  cloud-chatops/src/dev.py
  cloud-chatops/src/errors.py
  cloud-chatops/src/events.py
  cloud-chatops/src/features/base_feature.py
  cloud-chatops/src/features/post_to_dms.py
  cloud-chatops/src/features/pr_reminder.py
  cloud-chatops/src/find_prs.py
  cloud-chatops/src/pr_dataclass.py
  cloud-chatops/tests/test_base_feature.py
  cloud-chatops/tests/test_dev.py
  cloud-chatops/tests/test_events.py
  cloud-chatops/tests/test_find_prs.py
  cloud-chatops/tests/test_post_to_dms.py
  cloud-chatops/tests/test_pr_dataclass.py
  cloud-chatops/tests/test_pr_message_builder.py
  cloud-chatops/tests/test_pr_reminder.py
  cloud-chatops/version.txt
Labels: minor
