Repository stfc/cloud-docker-images, pull requests merged in 2025-05, with the labels that each got.

#118 Updating the github workflow runner image
  .github/workflows/cloud_chatops.yaml
Labels: documentation, workflow

#119 Chatops fixes
  cloud-chatops/README.md
  cloud-chatops/deployments/INSTALL.md
  cloud-chatops/deployments/deployment.yml
  cloud-chatops/deployments/docker-compose.yaml
  cloud-chatops/deployments/template_config.yml
  cloud-chatops/src/events/weekly_reminders.py
  cloud-chatops/src/helper/data.py
  cloud-chatops/src/main.py
  cloud-chatops/tests/test_data.py
  cloud-chatops/tests/test_read_config.py
  cloud-chatops/tests/test_weekly_reminders.py
  cloud-chatops/version.txt
Labels: major

#116 Rabbit consumers: Cover edge case of no image
  .pre-commit-config.yaml
  openstack-rabbit-consumer/rabbit_consumer/openstack_api.py
  openstack-rabbit-consumer/tests/test_openstack_api.py
  openstack-rabbit-consumer/version.txt
Labels: bug, patch
